# Generated by Django 3.0.3 on 2020-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=15)),
                ('Last_Name', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=25)),
                ('Contact', models.IntegerField()),
                ('Username', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=18)),
                ('Confirm_Password', models.CharField(max_length=18)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=6)),
                ('City', models.CharField(choices=[('Mum', 'Mumbai'), ('Che', 'Chennai'), ('Del', 'Delhi'), ('Kol', 'Kolkata'), ('Ban', 'Banglore'), ('Ind', 'Indore'), ('Hyd', 'Hyderabad'), ('Ahm', 'Ahmedbad'), ('Amr', 'Amritsar'), ('Jai', 'Jaipur')], max_length=10)),
                ('Address_Line_1', models.CharField(max_length=50)),
                ('Address_Line_2', models.CharField(max_length=50)),
            ],
        ),
    ]
