# Generated by Django 3.0.3 on 2020-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='Confirm_Password',
        ),
        migrations.AlterField(
            model_name='customers',
            name='Email',
            field=models.EmailField(max_length=25),
        ),
    ]
