# Generated by Django 3.0.3 on 2020-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0002_auto_20200328_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('First_Name', models.CharField(max_length=15)),
                ('Last_Name', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=25)),
                ('Contact', models.IntegerField()),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=18)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=6)),
                ('City', models.CharField(choices=[('Mum', 'Mumbai'), ('Che', 'Chennai'), ('Del', 'Delhi'), ('Kol', 'Kolkata'), ('Ban', 'Banglore'), ('Ind', 'Indore'), ('Hyd', 'Hyderabad'), ('Ahm', 'Ahmedbad'), ('Amr', 'Amritsar'), ('Jai', 'Jaipur')], max_length=10)),
                ('Address_Line_1', models.CharField(max_length=50)),
                ('Address_Line_2', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
