# Generated by Django 3.0.3 on 2020-03-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0004_auto_20200328_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='City',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Banglore', 'Banglore'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Ahmedbad', 'Ahmedbad'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur')], max_length=10),
        ),
    ]
