# Generated by Django 3.0.3 on 2020-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0005_auto_20200329_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
    ]
