# Generated by Django 3.0.3 on 2020-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0008_auto_20200402_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='PinCode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
