# Generated by Django 3.0.3 on 2020-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0010_auto_20200410_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=180),
        ),
    ]
