# Generated by Django 3.0.3 on 2020-04-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Houses', '0007_auto_20200401_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Needed_For', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Couple', 'Couple'), ('Kids(Below_15)', 'Kids(Below 15)'), ('Group', 'Group'), ('Customized', 'Others')], max_length=30)),
                ('Activity', models.CharField(choices=[('Yoga_Trainer', 'Yoga Trainer'), ('Fitness_Trainer', 'Fitness Trainer'), ('Dance_Trainer', 'Dance Trainer'), ('Karate_Trainer', 'Karate Trainer'), ('Swimming_Trainer', 'Swimming Trainer'), ('Customized', 'Others')], max_length=30)),
                ('Date_of_Complaint', models.DateTimeField(auto_now_add=True)),
                ('Preferred_Time', models.DateTimeField()),
                ('Description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Needed_For', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=5)),
                ('Activity', models.CharField(choices=[('Hair_Styling', 'Hair Styling'), ('Facial', 'Facial'), ('Beautician_&_Grooming', 'Beautician and Grooming'), ('Customized', 'Others')], max_length=25)),
                ('Date_of_Complaint', models.DateTimeField(auto_now_add=True)),
                ('Preferred_Time', models.DateTimeField()),
                ('Description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Plumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Type', models.CharField(choices=[('Taps_and_Leakages', 'Taps & Leakages'), ('Repairs_&_Fixes', 'Repairs & Fixes'), ('Home_Pipes_and_Taps_Fixing', 'Home : Pipes & Taps Fixing'), ('Installation', 'Installation'), ('Customized', 'Others')], max_length=40)),
                ('Date_of_Complaint', models.DateTimeField(auto_now_add=True)),
                ('Preferred_Time', models.DateTimeField()),
                ('Description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Massages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Needed_For', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=5)),
                ('Date_of_Complaint', models.DateTimeField(auto_now_add=True)),
                ('Preferred_Time', models.DateTimeField()),
                ('Description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='HouseKeeping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity', models.CharField(choices=[('Sofa_Cleaning', 'Sofa Cleaning'), ('Full_Home_Cleaning', 'Full Home Cleaning'), ('Bathroom_and_Toilets_Cleaning', 'Bathroom and Toilets Cleaning'), ('Kitchen_Cleaning', 'Kitchen Cleaning'), ('Backyard_Gardens_Terraces Cleaning', 'Back-yard/Gardens/Terraces Cleaning'), ('Customized', 'Others')], max_length=50)),
                ('Date_of_Complaint', models.DateTimeField(auto_now_add=True)),
                ('Preferred_Time', models.DateTimeField()),
                ('Description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Needed_For', models.CharField(choices=[('Repairs_&_Fixes', 'Repairs & Fixes'), ('House_Wiring_and_Short-Circuits', 'House Wiring & Short-Circuits'), ('Society_Electrical_Break-Downs', 'Society Electrical Break-Downs'), ('Device_Installation_and_Setup', 'Device Installation & Setup'), ('Customized', 'Others')], max_length=50)),
                ('Device', models.CharField(choices=[('Air_Conditioner', 'Air Conditioner'), ('Tube_lights', 'Tube-lights'), ('Fans', 'Fans'), ('Washing_Machines', 'Washing Machines'), ('Refridgerators', 'Refridgerators'), ('Televisions', 'Televisions'), ('Vacuum_Cleaners', 'Vacuum Cleaners'), ('Aqua_Guards', 'Aqua Guards'), ('Microwave', 'Microwave'), ('Gysers', 'Gysers'), ('Customized', 'Others')], max_length=50)),
                ('Preferred_Time', models.DateTimeField(auto_now_add=True)),
                ('Date_requested', models.DateTimeField()),
                ('Description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Customer')),
            ],
        ),
    ]
