# Generated by Django 3.0.3 on 2020-04-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0007_auto_20200401_1219'),
        ('Queries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massages',
            new_name='Massage',
        ),
        migrations.RenameModel(
            old_name='Plumbers',
            new_name='Plumber',
        ),
        migrations.RenameModel(
            old_name='Salons',
            new_name='Salon',
        ),
        migrations.RenameModel(
            old_name='Trainers',
            new_name='Trainer',
        ),
    ]
