# Generated by Django 3.0.3 on 2020-04-01 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0002_auto_20200401_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrical',
            name='Date_requested',
        ),
        migrations.AddField(
            model_name='electrical',
            name='Date_of_Complaint',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electrical',
            name='Preferred_Time',
            field=models.DateTimeField(),
        ),
    ]
