# Generated by Django 3.0.3 on 2020-04-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0003_auto_20200401_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrical',
            name='Address_of_Service',
            field=models.TextField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='Address_of_Service',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='massage',
            name='Address_of_Service',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='plumber',
            name='Address_of_Service',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='salon',
            name='Address_of_Service',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Address_of_Service',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='electrical',
            name='Description',
            field=models.TextField(default='Null'),
        ),
    ]
