# Generated by Django 3.0.3 on 2020-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0004_auto_20200402_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrical',
            name='Address_of_Service',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='electrical',
            name='Description',
            field=models.TextField(),
        ),
    ]
