# Generated by Django 3.0.3 on 2020-04-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0005_auto_20200402_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrical',
            name='Preferred_Date',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='Preferred_Date',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='massage',
            name='Preferred_Date',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='plumber',
            name='Preferred_Date',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='salon',
            name='Preferred_Date',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Preferred_Date',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical',
            name='Preferred_Time',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='housekeeping',
            name='Preferred_Time',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='massage',
            name='Preferred_Time',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='plumber',
            name='Preferred_Time',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='salon',
            name='Preferred_Time',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Preferred_Time',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
