# Generated by Django 3.0.3 on 2020-04-04 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0006_auto_20200403_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrical',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 12, 46, 16, 711104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housekeeping',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 12, 46, 16, 715096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='massage',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 12, 46, 16, 714099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plumber',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 12, 46, 16, 712105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salon',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 12, 46, 16, 714099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 12, 46, 16, 713102, tzinfo=utc)),
        ),
    ]
