# Generated by Django 3.0.3 on 2020-04-04 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0007_auto_20200404_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrical',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='housekeeping',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='massage',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plumber',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salon',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Date_of_Complaint',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
