# Generated by Django 3.0.3 on 2020-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0008_auto_20200404_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrical',
            name='PinCode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='PinCode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massage',
            name='PinCode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plumber',
            name='PinCode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='PinCode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='PinCode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
