# Generated by Django 3.0.3 on 2020-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0009_auto_20200404_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrical',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='massage',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plumber',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
    ]
