# Generated by Django 3.0.3 on 2020-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0010_auto_20200512_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrical',
            name='City',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Banglore', 'Banglore'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Ahmedbad', 'Ahmedbad'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='City',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Banglore', 'Banglore'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Ahmedbad', 'Ahmedbad'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massage',
            name='City',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Banglore', 'Banglore'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Ahmedbad', 'Ahmedbad'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plumber',
            name='City',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Banglore', 'Banglore'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Ahmedbad', 'Ahmedbad'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='City',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Banglore', 'Banglore'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Ahmedbad', 'Ahmedbad'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='City',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Banglore', 'Banglore'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Ahmedbad', 'Ahmedbad'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
