# Generated by Django 3.0.3 on 2020-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0011_auto_20200513_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrical',
            name='City',
            field=models.CharField(max_length=10),
        ),
    ]
